# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  pooja_thittamaranahalli_backendtasks-app:
    image: pooja_thittamaranahalli_backendtasks
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pooja_thittamaranahalli_backendtasks-postgresql:5432/pooja_thittamaranahalli_backendtasks
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://pooja_thittamaranahalli_backendtasks-postgresql:5432/pooja_thittamaranahalli_backendtasks
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  pooja_thittamaranahalli_backendtasks-postgresql:
    image: postgres:13.5
    # volumes:
    #   - ~/volumes/jhipster/pooja_thittamaranahalli_backendtasks/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pooja_thittamaranahalli_backendtasks
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
