apiVersion: v1
kind: Secret
metadata:
  name: pooja_thittamaranahalli_backendtasks-postgresql
  namespace: default
  labels:
    app: pooja_thittamaranahalli_backendtasks-postgresql
type: Opaque
data:
  postgresql-password: MjEwMTk1YjVlOWM4MzNhYTFkZWVlYmU2Y2IyN2E1YjBkNDBkOWUxYTUxNTZlNzhhMjVkN2M2YWRhZWNj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pooja_thittamaranahalli_backendtasks-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pooja_thittamaranahalli_backendtasks-postgresql
  template:
    metadata:
      labels:
        app: pooja_thittamaranahalli_backendtasks-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:13.5
          env:
            - name: POSTGRES_USER
              value: pooja_thittamaranahalli_backendtasks
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pooja_thittamaranahalli_backendtasks-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: pooja_thittamaranahalli_backendtasks-postgresql
  namespace: default
spec:
  selector:
    app: pooja_thittamaranahalli_backendtasks-postgresql
  ports:
    - port: 5432
