apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: pooja_thittamaranahalli_backendtasks
      context: ../../pooja_thittamaranahalli_backendtasks
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
